# Generated by Django 5.1.6 on 2025-03-03 09:52

import django.db.models.deletion
import django.template.defaulttags
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_book_destination_remove_service_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_et', models.DateTimeField(blank=True, default=django.template.defaulttags.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('messege', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('destination', models.CharField(choices=[('usa', 'Usa'), ('mexico', 'Mexico'), ('china', 'China'), ('japan', 'Japan'), ('italiy', 'Italiy')], default='usa', max_length=100)),
                ('request', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lenov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='index/img')),
                ('chegirma', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shadow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='index/img')),
                ('price', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Your_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='text1',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='text',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='about',
            name='price',
        ),
        migrations.AddField(
            model_name='about',
            name='img',
            field=models.ImageField(default=1, upload_to='index/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.shadow'),
        ),
    ]
