# Generated by Django 5.1.7 on 2025-03-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_contact_forma_lenov_shadow_your_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='bio',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='img',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text',
        ),
        migrations.AddField(
            model_name='about',
            name='course',
            field=models.CharField(default='lum', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
